### ISSUE TITLE
Create "$HOME/.pws" when not existent

### ISSUE THREAD

**Issue by syntonym** [tu500/pwm#1]
Currently stuff fails with 

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/syrn/git/pwm/pwm/__main__.py", line 112, in <module>
    main()
  File "/home/syrn/git/pwm/pwm/__main__.py", line 109, in main
    args.func(args)
  File "/home/syrn/git/pwm/pwm/__main__.py", line 32, in run_add_entry
    db_handler.add_entry(pwfile, entry_name, pw, entry_info)
  File "/home/syrn/git/pwm/pwm/db_handler.py", line 67, in add_entry
    entries = parse_dbfile(filename)
  File "/home/syrn/git/pwm/pwm/db_handler.py", line 12, in parse_dbfile
    with codecs.open(filename, 'rb', encoding='utf8') as f:
  File "/usr/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/syrn/.pws'
```

**Comment by tu500** [comment]
Fixed
